### ISSUE TITLE
Unable to deploy due to code coverage.

### ISSUE THREAD

**Issue by dcreeves88** [Up2Go/visualforce-table-grid#18]
Can't seem to get this into production due to code coverage. The git deploy tool fails, as do change sets from the sandbox to production. Git deploy fails with 66% coverage. Sandbox fails with 69% coverage. Any hints or idea's to get into production? Maybe I'm missing something. It looks like a lot of the tests are failing with this error: 

System.QueryException: List has no rows for assignment to SObject stack Class.TableGridTestHelper.userOfType

**Comment by dcreeves88** [comment]
I'v worked out a couple of the errors. A majority of the System.QueryExpeption errors were the result of a variable in the Test Helper class referencing a user that didn't exist. Changed that to a known users and it's passing all tests now. Still failing with 74% coverage. So close, so far! Any ideas?

**Comment by workinglouder** [comment]
I'm having the same trouble. Before there was profile that was stopping me from installing. They got rid of it earlier but I'm guessing these test fails are somehow related to it.

**Comment by KapilGoutam** [comment]
To fix this issue open below classes -
TableGridController_Test
TableGridTestHelper 
in both classes there is a variable "TESTUSER_PROFILE", changed this to "System Administrator".

final static String TESTUSER_PROFILE = 'System Administrator';

**Comment by up2go-rsoesemann** [comment]
Please use the fix provided above.
