### ISSUE TITLE
Deploy to Sandbox hangs in Queued forever

### ISSUE THREAD

**Issue by rrobinsoncpa** [Up2Go/visualforce-table-grid#20]
I work for a company who used a Salesforce consultant to build an app for us. One of the elements that the used is the Visualforce Table Grid that was created. They retained the attribution in the Visualforce TableGrid code. I wanted to reuse the code for another object within our Salesforce instances; however when I preview, all that appears is “Congratulations This is your new Component: tablegrid”. The consultants are gone, so I am trying to pick up the threads. My first question is if there is something that I have to install or activate to get the Table Grid to work in a different instance (sandbox)? 

My second question deals with stretching the functionality. Currently, the "New Record" button opens a new screen for data entry. Has anyone added code that creates a new line in the related list section that allows for data entry while on the same page?
 
Thank you for a cool solution.

**Comment by up2go-rsoesemann** [comment]
What do you mean by "when I preview it"? Did you add the component to a new Visualforce page by adding the <c:tableGrid> tag?

**Comment by rrobinsoncpa** [comment]
Ok. Let me back up. The tableGrid is in use in our production and QA environments.  I am trying to get it to work in one additional sandbox. I copied the code the other sandbox and the Visualforce page saves with no errors in the new sandbox. When I click the Preview button on the Visualforce page in the new sandbox, I see the "Congratulations" message, and that is all (no columns appear). If I open the Visualforce page in production or in QA and click the Preview button, I can at least see the columns which are to be displayed. I wondered if I need to install something in the new sandbox in order to display the columns rather than the "Congratulations" message.

**Comment by up2go-rsoesemann** [comment]
For every org where you want to use the tableGrid it needs to have all the code deployed. Best use the "Deploy to org" button from https://github.com/Up2Go/visualforce-table-grid/blob/master/README.md 

After a successful install all the sample pages should render as mentioned in the README. Eighter adapt or copy on of them and customize it for your needs.

**Comment by rrobinsoncpa** [comment]
Deployment is in process. Will advise to close this out. Thank you.

**Comment by rrobinsoncpa** [comment]
How long does it normally take to install? And are there any warnings, like do not close browser while processing (or something similar)?

**Comment by rrobinsoncpa** [comment]
This process has been running for 5 hours. Is that normal? If not, how do I stop it?

**Comment by rrobinsoncpa** [comment]
This process has run overnight, now it is throwing errors. How can it be stopped?

**Comment by rrobinsoncpa** [comment]
Still going. Is there any prep work that needs to be done before attempting to deploy (or after it starts?)

**Comment by up2go-rsoesemann** [comment]
I tried  it with 2 of my sandboxes and had no problems. Maybe you should retry. Also make sure that you click "Sandbox" when deploying.

**Comment by rrobinsoncpa** [comment]
Here are my steps:

1) Go to this URL: https://github.com/Up2Go/visualforce-table-grid/blob/master/README.md
2) Click deploy to Salesforce
3) Click Sandbox Radio Button
4) Click login to Salesforce
5) Sign into the desired sandbox
6) See the GitHub login screen
7) Click the Deploy button
8) I see the “Deployment Started” message
9) I see the “Status: Queued” message repeat. And repeat. And repeat. Over 100 times
10) This continues all day and all night, and the artifacts never install

I just started it again for the 6th time. Still seeing the “Status: Queued” message

Robert L Robinson
Manager, Salesforce Application

[cid:image002.jpg@01D0FB5B.BD9097F0]


Welltower Inc.
4500 Dorr Street
Toledo, Ohio 43615-4040
419.247.2860 (o)
419.699.2539 (m)
rrobinson@welltower.com<mailto:rrobinson@welltower.com>



Please note my new welltower.com email address.

**Comment by rrobinsoncpa** [comment]
I still see "Status: Queued" messages cascading on my screen.

**Comment by rrobinsoncpa** [comment]
Ran all day. Never finished.

**Comment by rrobinsoncpa** [comment]
Tried another sandbox. Seeing the "queued" message on that install as well...

**Comment by rrobinsoncpa** [comment]
Is there any other way to deploy to a sandbox?
Or, do you have a list of the artifacts that I could harvest from the sandbox where it was successfully deployed back in September of last year (via change set)? Thank you for your help.

**Comment by up2go-rsoesemann** [comment]
@rrobinsoncpa please stop posting hourly updates. This is an open source project and not a customer hotline. I have no answer at the moment and others might not be willing to read hundreds of repeating comments :-(

**Comment by rrobinsoncpa** [comment]
Trust me, I am done. My anxiety stems from this being a mission critical process, and that your solution was the most elegant available.
I think the best alternative is what I mentioned in the last email; to gather up the artifacts from our QA Sandbox from September and copy them to the sandbox where I am testing. I have searched for such a list, but have not found it. If you can point me to it, I will go away.
