### ISSUE TITLE
Issues with installing

### ISSUE THREAD

**Issue by rrobinsoncpa** [Up2Go/visualforce-table-grid#21]
Has anyone else had issues with installation (deployment)? I went to the Visualforce-Table-Grid page yesterday and clicked the Deploy button to set this up in a sandbox. I saw the "Status: Queued" message hundreds of times, but the deployment has not completed. Are there any helpful hints as the how I can get this deployed? Thanks.

**Comment by up2go-rsoesemann** [comment]
Duplicate of #20
