### ISSUE TITLE
Add and remove filters to tableGrid using a class on ajax dynamic call

### ISSUE THREAD

**Issue by gabrielacosta** [Up2Go/visualforce-table-grid#23]
Hi, 
I think your implementation is quite nice. I'm trying to add some dynamic ajax for specific properties search. 

I want to know if it possible to recover the tablegrid from a class and added or removed filters. 
Also, I will like to know if you can provide some example of the filters.
 
I want to add the same that you have in this part.

![image](https://cloud.githubusercontent.com/assets/8519425/23496303/802872d6-ff71-11e6-9dd1-dafe2714d8bd.png)

But with a dynamic load based on ajax.
I'm using this type of implementation and I already connected the javascript to the page. 
<c:tableGrid type="Opportunity" 
                         fields="Name,StageName,Amount,CloseDate" 
                         filter="AccountId = `{!Account.Id}`"
                         sortBy="Name" 
                         sortDescending="true"
                         title="Opportunities" 
                         gridPageId="editable"
                         customizeFields="true"
                         customizeFilter="true"
                         pageSize="5"
                         mode="edit"/>  

Could you please help me with those details? 

Kind regards, 

Juan

**Comment by up2go-rsoesemann** [comment]
Very cool to see contributing. How exactly can I help you?

**Comment by gabrielacosta** [comment]
Could you please explain to me how the tablegrid added the filters manually?

I need to understand where I can add some methods to insert the filters using javascripts calls.

**Comment by up2go-rsoesemann** [comment]
What do you mean with "manually"?  The part of the UI where you can set Filter Conditins?

The component is called https://github.com/Up2Go/visualforce-table-grid/blob/master/src/components/whereClauseBuilder.component
and its Controller https://github.com/Up2Go/visualforce-table-grid/blob/master/src/classes/WhereClauseBuilderCtrl.cls

I guess adding some AJAX magic there will do the trick.

The `<c:tableGrid filter="">` attribute is not modified by this UI. Its fixed. You cannot modify it from the UI.

**Comment by gabrielacosta** [comment]
Can I have access to the WhereClauseBuilderCtrl.cls from the table grid class? 
Because if there is not overload in the filter property in the tableGrid, the only way is accessing directly to that object and adding the filters like that.

**Comment by gabrielacosta** [comment]
Hi rsoesemann, 

I already advance in the implementation. 

![image](https://cloud.githubusercontent.com/assets/8519425/23540781/7fa5368e-0037-11e7-9dc0-4c1498a305e1.png)


Currently, I have to control for the new page (a custom extension). 
The first control helps me to manage the dynamic ajax data entering and onchange update. 
The second on is the normal tablegrid that you created. 

Based on you advance lookup, I found a way to add the filter parameters using the 
searchFilter="{!searchFilter}" parameter. 

I received the fields for the dynamic search from the page and I can review which one is depending on the field name. 

I only have one problem. I need to access the TableGridController on the new extension. Could help figuring out how to get that parameter. One way could be overloading the tablegrid.vfc and adding a value parameter
So, I can do something like this

![image](https://cloud.githubusercontent.com/assets/8519425/23540858/02792aca-0038-11e7-97aa-be3a2c2e4fbc.png)

It is possible to do that. Because, if I can get the table grid I can force the refresh of the grid and it will be finished. 

That's the part that I need your help. 

Could you guide me how can achieve this?
Or if you now another way that I can have access to the original table grid and call the refresh from the new control It will solve my problem. 
Maybe, can I get the refresh dynamic id of the button even if the settings panel is collapsed?  and call the refresh from the controller. Well some ideas...

Anyway, if you can help me. I will be waiting for your answer. 

Kind regards, 

Juan

**Comment by up2go-rsoesemann** [comment]
@gabrielacosta Please read https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ on how to contribute to a Github project.

You don't need access to my repo. Just fork and extend it. After you are don you can create a Pull Request to merge your changes back into my repo.
