### ISSUE TITLE
It is possible to have a paging of 50,100 and 200 in the controls.

### ISSUE THREAD

**Issue by gabrielacosta** [Up2Go/visualforce-table-grid#24]
Hi, 

I want to know if it is possible to have more registers loading in the controls. I found a comment in the code saying, that you found problems with the implementation.

![image](https://cloud.githubusercontent.com/assets/8519425/23735973/415f3410-04dd-11e7-850d-86370c9098c8.png)

Could you please let me know the status of this issue. 

Kind regards, 

Juan

**Comment by up2go-rsoesemann** [comment]
Depends on your org. You should try it out.
