### ISSUE TITLE
Unable to Directly Deploy or Migrate

### ISSUE THREAD

**Issue by cjsigler** [Up2Go/visualforce-table-grid#3]
Hello.  When I attempt to directly deploy I get the following errors:
Failures:
components/tableGrid.component(tableGrid):That component name is already in use or has been previously used, please choose a different one.
profiles/U2G_TestUserProfile.profile(U2G_TestUserProfile):Unknown user permission: EditPublicReports
pages/advancedLookup.page(advancedLookup):Unsupported attribute type in  in advancedLookup at line 42 column 47
pages/tableGridRelatedList.page(tableGridRelatedList):Unsupported attribute type in  in tableGridRelatedList at line 49 column 35
pages/tableGridStandalone.page(tableGridStandalone):Unsupported attribute type in  in tableGridStandalone at line 53 column 37

  I was able to grab the code and have Force.com installed but cannot figure out what to do next.  

Any assistance would be appreciated.

CSigler

**Comment by up2go-rsoesemann** [comment]
I finally removed the problematic profile. The repo should now install without any failure. Thanks for you interest in this repo and you patience ;-)
