### ISSUE TITLE
U2G_TestUserProfile.profile is Failing to Load (Unknown User Permission:  AllowUniversalSearch)

### ISSUE THREAD

**Issue by vzw2t9** [Up2Go/visualforce-table-grid#4]
I get the following error when attempting to deploy using GitHub Salesforce Deply Tool

Deployment Started
Status: Queued
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: InProgress
Status: Completed
Deployment Complete
Failures:
profiles/U2G_TestUserProfile.profile(U2G_TestUserProfile):Unknown user permission: AllowUniversalSearch

**Comment by joelati** [comment]
Hi cjsigler,

I am struggling with the same issue deploying to my Salesforce environment. You mention "I removed the Profile and installed all files." 

How did remove the Profile from the deployment?

Thanks, 
Joel

**Comment by cjsigler** [comment]
I was never able to get the application to install properly.  Instead I saved locally and copied files as needed into Mavensmate (Salesforce).  Sadly, I was not able to use TableGrid due to limitations, but had to create what I needed from scratch.

**Comment by joelati** [comment]
Ahhh, that makes sense. Thanks for the info. 
May I ask what the limitations were in TableGrid that lead you to creating your own?

**Comment by workinglouder** [comment]
I'm having the same problem, can't deploy to the sandbox. Get this error message, and none of the components are present afterwards. Anyone find a way to solve this?

**Comment by workinglouder** [comment]
Other packages online seem to have this problem, looks like the only solution is to remove the profile permission, or just the whole profile from the component install. Is there a way to do this easily?

If not, is there any chance the owner of this could remove the profile from the package, others seem to have had this problem. It seems a shame that such a great looking package should become so problematic to install.

**Comment by up2go-rsoesemann** [comment]
I finally removed the problematic profile. The repo should now install without any failure. Thanks for you interest in this repo and you patience ;-)
