### ISSUE TITLE
Not able to deploy it to my Salesforce accounts

### ISSUE THREAD

**Issue by ankit851gupta** [Up2Go/visualforce-table-grid#9]
Hi ,

I have been trying hard to deploy the visualforce-table-grid package into my organization's sandbox account and my developer account as well. I have no idea why "AllowUniversalSearch" error in sandbox and "EditPublicReport" error my developer accout are coming.

I am new to Github also...i know if we take off the profile..this deployment should happen..but i have no idea how to take it off...please help me.

**Comment by up2go-rsoesemann** [comment]
Just read the thread of this issue https://github.com/Up2Go/visualforce-table-grid/issues/4
It's talking about exactely that.

**Comment by up2go-rsoesemann** [comment]
I finally removed the problematic profile. The repo should now install without any failure. Thanks for you interest in this repo and you patience ;-)
